static bool DAY_Z_LIFE_DEBUG = true;
static int DAY_Z_LIFE_EVENT_GET_CONFIG_RESPONSE = 2222218;
static int DAY_Z_LIFE_EVENT_GET_CONFIG = 2222219;
static int DAY_Z_LIFE_OPEN_GET_BUILDING_DATA = 222220;
static int DAY_Z_LIFE_OPEN_GET_BUILDING_DATA_RESPONSE = 222221;
static int DAY_Z_LIFE_OPEN_BUY_BUILDING = 222222;
static int DAY_Z_LIFE_OPEN_BUY_BUILDING_RESPONSE = 222223;
static int DAY_Z_LIFE_OPEN_SELL_BUILDING = 222224;
static int DAY_Z_LIFE_OPEN_SELL_BUILDING_RESPONSE = 222225;
static int DAY_Z_LIFE_GET_PLAYER_BUILDING = 222226;
static int DAY_Z_LIFE_GET_PLAYER_BUILDING_RESPONSE = 222227;
static int DAY_Z_LIFE_BUY_STORAGE = 222228;
static int DAY_Z_LIFE_BUY_STORAGE_RESPONSE = 222229;
static int DAY_Z_LIFE_SELL_STORAGE = 222230;
static int DAY_Z_LIFE_SELL_STORAGE_RESPONSE = 222231;



static string DAY_Z_LIFE_SERVER_FOLDER_BASE = "$profile:DayZLife\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA = "$profile:DayZLife\\Data\\";
static string DAY_Z_LIFE_SERVER_FOLDER_CONFIG = "$profile:DayZLife\\Config\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA_HOUSE = "$profile:DayZLife\\Data\\House\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA_PLAYER = "$profile:DayZLife\\Data\\Player\\";