static bool DAY_Z_LIFE_DEBUG = false;
enum DZL_RPC {
    EVENT_GET_CONFIG = 2222219,
    PLAYER_DATA,
    PLAYER_DATA_RESPONSE,
    PLAYER_BANK_DATA,
    PLAYER_BANK_DATA_RESPONSE,
    PLAYER_DEPOSIT_AT_BANK_DATA,
    PLAYER_DEPOSIT_TO_PLAYER,
    PLAYER_DEPOSIT_TO_PLAYER_RESPONSE,
    ALL_PLAYER_IDENT_DATA,
    ALL_PLAYER_IDENT_DATA_RESPONSE,
    BUY_LICENCE,
    BUY_LICENCE_RESPONSE,
    BUY_LICENCE_USE,
    BUY_LICENCE_USE_RESPONSE,
    RECEIVE_MESSAGE,
    TRADE_ACTION,
    TRADE_ACTION_RESPONSE,
    MONEY_TRANSFER,
    NEW_SPAWN_CLIENT,
    NEW_SPAWN,
    NEW_SPAWN_RESPONSE,
    ALL_PLAYER_ONLINE_PLAYERS,
    ALL_PLAYER_ONLINE_PLAYERS_RESPONSE,
    ALL_PLAYER_UPDATE_JOB_PLAYERS,
    LOAD_OUT,
    LOAD_OUT_RESPONSE,
    ARREST_PLAYER,
    ARREST_PLAYER_RESPONSE,
    GET_ESCAPED_PLAYERS,
    GET_ESCAPED_PLAYERS_RESPONSE,
    GET_ALL_PLAYERS,
    GET_ALL_PLAYERS_RESPONSE,
    DELETE_PLAYER,
    HARVEST,
    GET_CAR_KEYS,
    GET_CAR_KEYS_RESPONSE,
    GET_UPDATE_CAR_KEYS,
    GET_DAY_Z_LIFE_ALL_PLAYER_ONLINE_PLAYERS_FOR_ALL,
    GET_DAY_Z_LIFE_ALL_PLAYER_ONLINE_PLAYERS_FOR_ALL_RESPONSE,
    UPDATE_CAR_FROM_PLAYER_SIDE,
    UPDATE_CAR,
    EVENT_GET_CONFIG_RESPONSE_BANKING,
    EVENT_GET_CONFIG_RESPONSE_JOB,
    EVENT_GET_CONFIG_RESPONSE_LICENCE,
    EVENT_GET_CONFIG_RESPONSE_TRADER,
    EVENT_GET_CONFIG_RESPONSE_SPAWN_POINTS,
    EVENT_GET_CONFIG_RESPONSE_ADMIN_IDS,
    EVENT_GET_CONFIG_RESPONSE_HOUSE_CONFIG,
    EVENT_GET_CONFIG_TRADER,
    EVENT_GET_CONFIG_BANKING,
    MONEY_TRANSFER_ADMIN,
    EVENT_GET_CONFIG_CAR_RESPONSE,
    EVENT_STORE_CAR,
    EVENT_GET_CAR_FROM_STORAGE,
    EVENT_GET_CAR_DATA_FROM_STORAGE,
    EVENT_GET_CAR_DATA_FROM_STORAGE_RESPONSE,
    EVENT_CAR_RAID,
    EVENT_MEDIC_KILL_PLAYER,
    EVENT_HOSPITAL_HEAL_PLAYER,
    EVENT_GET_CONFIG_MEDIC_RESPONSE,
    GET_EMERGENCY_CALLS,
    GET_EMERGENCY_CALLS_RESPONSE,
    MEDIC_CALL,
    RECEIVE_MEDIC_MESSAGE,
    EVENT_CLIENT_SHOULD_REQUEST_PLAYER_BASE,
    ALL_PLAYER_UPDATE_MEDIC_PLAYERS,
    ALL_WAS_HEALED_RESPONSE,
    PLAYER_SERVER_RESET_AT_PLAYER_BASE,
    OPEN_GET_BUILDING_INVENTORY_DATA,
    OPEN_GET_BUILDING_INVENTORY_DATA_RESPONSE,
    SEND_MESSAGE,
    SEND_MESSAGE_SERVER,
    RECEIVE_MESSAGE_CLIENT,
    RECEIVE_ONLINE_PLAYERS,
    RECEIVE_ONLINE_PLAYERS_RESPONSE,
    BANK_RAID_CANCELED,
    BANK_RAID_FINISHED,
    EVENT_GET_CONFIG_RESPONSE_BASE_BUILDING,
    GET_MEDIC_COUNT,
    GET_MEDIC_COUNT_RESPONSE,
    CHANGE_CAR_OWNER,
    START_ROB_MONEY_FROM_SHOP,
    PAY_ROB_MONEY_FROM_SHOP,
    EVENT_GET_CONFIG_RESPONSE_CRIME,
    CREATE_TICKET,
    CREATE_TICKET_RESPONSE,
    PAY_TICKET,
    GET_OPEN_TICKET_PLAYERS,
    GET_OPEN_TICKET_PLAYERS_RESPONSE,
    ALL_PLAYER_UPDATE_ARMY_PLAYERS,
    EVENT_GET_CONFIG_RESPONSE_ARMY,
    EVENT_GET_CONFIG_TRADER_STORAGE,
    EVENT_GET_CONFIG_TRADER_STORAGE_RESPONSE,
    GET_FRACTION,
    GET_FRACTION_RESPONSE_FRACTION_OWNER,
    GET_UPDATE_FRACTION_MEMBERS,
    GET_UPDATE_FRACTION_MEMBERS_RESPONSE,
    DELETE_FRACTION,
    GET_FRACTION_RESPONSE_FRACTION_MEMBER,
    FRACTION_MEMBER_LEAVE,
    FRACTION_MEMBER_LEAVE_RESPONSE,
    GET_FRACTION_RESPONSE_NOT_A_FRACTION_MEMBER,
    FRACTION_MEMBER_JOIN,
    FRACTION_MEMBER_JOIN_RESPONSE,
    FRACTION_CREATE_FRACTION,
    DELETE_FRACTION_RESPONSE,
    EVENT_GET_CONFIG_RESPONSE_MESSAGE,
    EVENT_SEND_CONTACT,
    EVENT_GET_CONFIG_RESPONSE_TUNING_CONFIG,
    EVENT_TUNE_CAR,
    RELOAD_CONFIG,
}

static string DAY_Z_LIFE_SERVER_FOLDER_BASE = "$profile:DayZLife\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA = "$profile:DayZLife\\Data\\";
static string DAY_Z_LIFE_SERVER_FOLDER_CONFIG = "$profile:DayZLife\\Config\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA_CAR = "$profile:DayZLife\\Data\\Car\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA_PLAYER = "$profile:DayZLife\\Data\\Player\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA_ITEM_STORAGE = "$profile:DayZLife\\Data\\ItemStorage\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA_FRACTION = "$profile:DayZLife\\Data\\Fraction\\";
static string DAY_Z_LIFE_LOGS = "$profile:DayZLife\\Logs\\";

static string DAY_Z_LIFE_JOB_COP = "Cop";
static string DAY_Z_LIFE_JOB_MEDIC = "Medic";
static string DAY_Z_LIFE_JOB_CIVIL = "Civil";
static string DAY_Z_LIFE_JOB_ARMY = "Army";

static string DAY_Z_LIFE_ACCESS_PLAYERS = "Players";
static string DAY_Z_LIFE_ACCESS_CARS = "Cars";

static string DAY_Z_LIFE_DZL_PLAYER_DEAD_STATE_NONE = "none";
static string DAY_Z_LIFE_DZL_PLAYER_DEAD_STATE_NEW_SPAWN_MEDIC = "MEDIC";
static string DAY_Z_LIFE_DZL_PLAYER_DEAD_STATE_NEW_SPAWN_HOSPITAL = "HOSPITAL";
static string DAY_Z_LIFE_DZL_PLAYER_DEAD_STATE_IS_BETWEEN = "BETWEEN";

//static bool DEVELOPER = true;
