static int DAY_Z_LIFE_EVENT_GET_CONFIG = 58585100;
static int DAY_Z_LIFE_RECEIVE_MESSAGE = 58585101;
static int DAY_Z_LIFE_EVENT_GET_CONFIG_RESPONSE_MESSAGE = 58585102;
static int DAY_Z_LIFE_SEND_MESSAGE = 58585103;
static int DAY_Z_LIFE_SEND_MESSAGE_SERVER = 58585104;
static int DAY_Z_LIFE_RECEIVE_MESSAGE_CLIENT = 58585105;
static int DAY_Z_LIFE_EVENT_SEND_CONTACT = 58585106;
static int DAY_Z_LIFE_RECEIVE_ONLINE_PLAYERS = 58585107;
static int DAY_Z_LIFE_RECEIVE_ONLINE_PLAYERS_RESPONSE = 58585108;

static string DAY_Z_LIFE_SERVER_FOLDER_BASE = "$profile:TBMessenger\\";
static string DAY_Z_LIFE_SERVER_FOLDER_DATA = "$profile:TBMessenger\\Data\\";
static string DAY_Z_LIFE_SERVER_FOLDER_CONFIG = "$profile:TBMessenger\\Config\\";
